# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cameron Tarbotton's Personal Website
email: info@camerontarbotton.com
description: Insights on what matters most.
baseurl: "cameron-personal" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: beckyscholar
fb_admins: "https://www.facebook.com/cameron.tarbotton"
fb_appid: 1707383322824946
gems:
- jekyll-email-protect
- jekyll-sitemap


# Build settings
markdown: kramdown


